### PR TITLE
save node text to scene

### PR DESCRIPTION
**Pull request by nodeshareio**

### CODE REVIEW

**Comment by wildiness** [comment]
Ok :+1: , but why is this needed? :thinking:

**Comment by nodeshareio** [comment]
> Ok 👍 , but why is this needed? 🤔
I have more addon code, but it uses requests to communicate with my server (authentication so far), so should be opt-in.
Once it is more ready for github we can see about merging, or have a separate addon for this functionality. 

I could use the clipboard, however this way I can check for node text, store multiple node strings by grabbing the current global property, and send any to the server for submission testing.

**Comment by wildiness** [comment]
Ok :100: . Add a version bump :arrow_up:  to 0.1.5 in nodesharer.py and \_\_init__ and I will merge :heavy_check_mark: . If that's not possible I will version bump afterwards. :+1:

**Comment by nodeshareio** [comment]
Can do this evening, thanks!😎

**Pull request merged**
